require 'b2b_center_api/web_service/types/auction_participant'
require 'b2b_center_api/web_service/types/firm_info'
require 'b2b_center_api/web_service/types/auction_offer'
require 'b2b_center_api/web_service/types/b2b_file'
require 'b2b_center_api/web_service/types/array_of_ids'
