AllCops:
  RunRailsCops: false

AsciiComments:
  Enabled: false

StringLiterals:
  Enabled: false

ClassLength:
  Enabled: false

MethodLength:
  Enabled: false

Documentation:
  Enabled: false

LineLength:
  Max: 119
